// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yemdnyotxvcvqteruvow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllbWRueW90eHZjdnF0ZXJ1dm93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDE0MTcsImV4cCI6MjA2NjM3NzQxN30.N-owemAzAlDOCqQKyeKcl-RwcEvL-PiYy-CK5dNIwJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});